exclude = ["__init__.py"]

[lint]
select = ["A", "B006", "D", "E", "F", "I", "W", "UP"]
ignore = [
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D413", # Missing blank line after last section
    "UP031", # Use format specifiers instead of percent format
]

[pydocstyle]
convention = "numpy"
ignore-decorators = [
    "property",
    "setter",
]

[per-file-ignores]
"skada/**/test_*.py" = [
    "D103", # Missing docstring in public function
]
"examples/*/*.py" = [
    "D205", # 1 blank line required between summary line and description
]
